typography_spectrum: 0.7806907738558948
color:
  brandStrength: 0.825054171262309
  lightness: 0.7350944955833256
  saturation: 0.9386840627994388
  rhythmicContrast: 0.5111677763052285
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.24296750640496612
author:
  name: Benita Grace Joy
  email: benita.joy@gmail.com
  url: ''
name: Good Therapy Toronto
title: >-
  Marriage and Family Therapy, Forensic Psychotherapy, and Life Coaching
  Services
